### ISSUE TITLE
Can I display a non HTTPS page?

### ISSUE THREAD

**Issue by yannickoo** [PrestoDoctor/react-native-browser#3]
You mentioned in another issue that you recently updated the `TOWebViewController` – I guess I cannot use non HTTPS pages like `http://example.com` now but HTTPS pages work fine. I get a white page and I see the URL in the header.

Can you confirm that?

**Comment by mfkp** [comment]
That's odd, I guess I only tested https sites, so I'll test it with http when I get back home tonight to confirm

**Comment by mfkp** [comment]
@yannickoo I just tried with a few http sites and they seemed to load just fine. What site is giving you a problem? Are you still able to reproduce the issue?

**Comment by yannickoo** [comment]
@mfkp did you test the URL I sent you? 😇

**Comment by yannickoo** [comment]
I see non HTTPS sites like this: white page but there is always something black (I need to scroll down in order to see this) :/

<img width="487" alt="screen shot 2016-07-30 at 20 24 13" src="https://cloud.githubusercontent.com/assets/1086961/17272329/d758c7fe-5693-11e6-8413-679328ce07ef.png">

**Comment by zcei** [comment]
Hej, I saw your code is using `initWithURL`, so [this comment](https://github.com/TimOliver/TOWebViewController/issues/71#issuecomment-166005708) is likely related.

**Comment by mfkp** [comment]
Hey sorry about the delay - was traveling for a while, I'll test it out soon.

**Comment by yannickoo** [comment]
Okay, I could finally fixed it by settings `NSAppTransportSecurity` value properly in the `Info.plist` 

http://stackoverflow.com/questions/31534304/does-app-store-reject-submission-if-nsallowsarbitraryloads-set-to-yes

**Comment by yannickoo** [comment]
There is also a closed issue for this - https://github.com/TimOliver/TOWebViewController/issues/67
